version: 2
jobs:
  test:
    working_directory: ~/sitemap-webpack-plugin
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test against webpack 4
          command: yarn test:webpack4
      - run:
          name: Test against webpack 5
          command: yarn test:webpack5
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Coveralls
          command: yarn coveralls
      
workflows:
  version: 2
  test:
    jobs:
      - test
